# Generated by Django 6.0.1 on 2026-02-25 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (e.g. 10 for 10%)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount to apply this coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
