# Generated by Django 6.0.1 on 2026-02-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_is_active_coupon_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.FloatField(default=0.0, help_text='Minimum order amount to apply this coupon'),
        ),
    ]
