# Generated by Django 6.0.1 on 2026-02-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_coupon_minimum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_first_order_only',
            field=models.BooleanField(default=False, help_text='If checked, this coupon can only be used on the first order'),
        ),
    ]
