# Generated by Django 6.0.1 on 2026-03-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('login', 'User Login'), ('order', 'New Order'), ('return', 'Product Return'), ('stock', 'Low Stock'), ('payment', 'Payment Failed'), ('coupon', 'Coupon Expiry'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='related_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
