# Generated by Django 6.0.1 on 2026-03-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_status_alter_order_status_and_more'),
        ('products', '0006_alter_product_stock_productsize_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size'),
        ),
        migrations.DeleteModel(
            name='OrderTracking',
        ),
    ]
