# Generated by Django 6.0.1 on 2026-03-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_size_delete_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Cancellation Requested', 'Cancellation Requested'), ('Cancel Request Rejected', 'Cancel Request Rejected'), ('Return Requested', 'Return Requested'), ('Returned', 'Returned')], default='Pending', max_length=30),
        ),
    ]
